name: python-ci.yml

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Required on macOS to build gmp package
      - name: Install autoconf
        run: brew install autoconf-archive libtool automake pkgconf pkg-config
        if: ${{ runner.os == 'macOS' }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Compile build dependencies
        run: |
          pip install pip-tools
          pip-compile --all-build-deps --output-file=requirements-ci.txt --strip-extras ./python/pyproject.toml

      - name: Install build dependencies
        run: pip install -r requirements-ci.txt

      - name: Install CI dependencies
        run: pip install ruff pytest

      - name: Lint
        run: ruff check ./python/sqsgenerator --output-format=github

      - name: Format
        run: ruff format --diff ./python/sqsgenerator

      - name: Build Package
        run: pip install ./python -v  --no-build-isolation
        if: ${{ runner.os != 'macOS' }}


      - name: Run unit tests
        run: pytest ./python -vv --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}-${{ matrix.os }}.xml
        if: ${{ runner.os != 'macOS' }}

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}-${{ matrix.os }}
          path: junit/test-results-${{ matrix.python-version }}-${{ matrix.os }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      - name: Build ctest executables
        run: ${{ github.workspace }}/scripts/build-tests.sh build
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}

      - name: Run ctest
        run: ctest --test-dir ${{ github.workspace }}/build/tests --verbose --output-junit ${{ github.workspace }}/junit/test-results-${{ matrix.os }}.xml
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}


      - name: Build CLI app
        run: ${{ github.workspace }}/scripts/build-tests.sh build
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}

      - name: Run sqsgen --version
        run: ${{ github.workspace }}/build/sqsgen --version
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}

      - name: Upload ctest test results
        uses: actions/upload-artifact@v4
        with:
          name: ctest-results-${{ matrix.os }}
          path: junit/test-results-${{ matrix.os }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
