name: WebAssembly Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - wasm

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: "-manifests"
  EM_VERSION: 4.0.11
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VCPKG_BINARY_SOURCES: "x-gha,readwrite"
      VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg_installed

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '')

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}

      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - uses: friendlyanon/setup-vcpkg@v1

      - name: Verify Emscripten installation
        run: emcc -v

      - name: Build WebAssembly libraries
        run: ${{ github.workspace }}/scripts/build-wasm.sh build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: build/js/wasm/core.{js,wasm,d.ts}
